---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: panoptica
  namespace: panoptica
spec:
  interval: 5m
  releaseName: panoptica
  chart:
    spec:
      chart: panoptica-kubernetes-integration
      sourceRef:
        kind: HelmRepository
        name: panoptica
        namespace: panoptica
      interval: 1m