---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: panoptica
  namespace: panoptica
spec:
  type: oci
  interval: 5m0s
  url: oci://public.ecr.aws/ciscoeti/panoptica/charts