apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: panopticaaccount.kopf.dev
spec:
  scope: Namespaced
  group: kopf.dev
  names:
    kind: PanopticaAccount
    plural: panopticaaccounts
    singular: panopticaaccount
    shortNames:
      - pca
      - pcas
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
